"use client";

import Link from "next/link";
import { useState } from "react";
import { Card, Disclaimer } from "@/components/PageHeader";
import { LocalOnlyNotice } from "@/components/passport/PassportChrome";
import { usePatient } from "@/lib/context/PatientContext";
import { runFhirImport, type FhirImportResult } from "@/lib/fhir/importer";
import { IMPORT_CONTENTS } from "@/lib/fhir/source";
import { SYNTHEA_PATIENT_ID, syntheaDemoSource } from "@/lib/fhir/syntheaSource";
import { countItems, describeBatch } from "@/lib/passport/importPlan";

type Step = "ready" | "importing" | "done" | "error";

export default function SyntheaImportPage() {
  const { patientId, setPatientId, record } = usePatient();
  const [step, setStep] = useState<Step>("ready");
  const [result, setResult] = useState<FhirImportResult | null>(null);
  const [error, setError] = useState<string | null>(null);
  const isSyntheaPatient = patientId === SYNTHEA_PATIENT_ID;

  async function importRecord() {
    setStep("importing");
    setError(null);
    try {
      setResult(await runFhirImport(syntheaDemoSource, patientId, record));
      setStep("done");
    } catch (reason) {
      setError(reason instanceof Error ? reason.message : "The synthetic record could not be imported.");
      setStep("error");
    }
  }

  return (
    <div className="mx-auto max-w-3xl space-y-5">
      <div>
        <Link href="/passport/add/" className="inline-flex min-h-11 items-center text-sm font-semibold text-brand-700 hover:text-brand-900">← Add to my Passport</Link>
        <h2 className="font-serif text-2xl font-semibold text-navy">Import a Synthea patient</h2>
        <p className="mt-1 text-sm text-ink-soft">A realistic, entirely synthetic FHIR R4 health record for testing the complete app flow.</p>
        <LocalOnlyNotice className="mt-2" />
      </div>

      <p className="rounded-xl border border-brand-200 bg-brand-50 px-4 py-3 text-sm text-brand-900">
        <strong>Synthetic demo data.</strong> This record was generated by Synthea and does not describe a real person. It is bundled with the app, so no account or health-system connection is used.
      </p>

      {!isSyntheaPatient ? (
        <Card className="p-5">
          <h3 className="font-serif text-xl font-semibold text-navy">Open the import-ready sample patient</h3>
          <p className="mt-2 text-sm text-ink-soft">
            Imports are matched to the person named in the record. Switch from {record.patient.name} to the empty Synthea Passport before loading its data.
          </p>
          <button type="button" onClick={() => setPatientId(SYNTHEA_PATIENT_ID)} className="mt-5 min-h-12 rounded-full bg-brand-700 px-5 text-sm font-semibold text-white hover:bg-brand-800">
            Switch to Synthea sample patient
          </button>
        </Card>
      ) : (
        <>
          {step === "ready" && (
            <Card className="p-5">
              <h3 className="font-serif text-xl font-semibold text-navy">Build {record.patient.name}&apos;s Passport</h3>
              <p className="mt-1 text-sm text-ink-soft">
                Parthia will parse the Bundle into separate reviewable items. Nothing enters safety analysis until you confirm it.
              </p>
              <ul className="mt-4 grid gap-2 text-sm sm:grid-cols-2">
                {IMPORT_CONTENTS.slice(0, 9).map((item) => (
                  <li key={item.label} className="rounded-xl border border-line bg-cream/50 px-3 py-2">
                    <span className="font-semibold text-ink">{item.label}</span>
                    <span className="block text-xs text-ink-muted">FHIR {item.resource}</span>
                  </li>
                ))}
              </ul>
              <button type="button" onClick={importRecord} className="mt-5 min-h-12 rounded-full bg-brand-700 px-5 text-sm font-semibold text-white hover:bg-brand-800">
                Import synthetic FHIR record
              </button>
            </Card>
          )}

          {step === "importing" && (
            <Card className="p-5">
              <p role="status" className="flex items-center gap-3 text-sm text-ink">
                <span aria-hidden className="h-5 w-5 animate-spin rounded-full border-2 border-brand-300 border-t-brand-700" />
                Parsing conditions, medications, allergies, results, visits and care plans…
              </p>
            </Card>
          )}

          {step === "error" && (
            <Card className="p-5" accent="border-l-attention">
              <p role="alert" className="font-semibold text-attention">{error}</p>
              <button type="button" onClick={() => setStep("ready")} className="mt-3 min-h-11 rounded-full px-4 text-sm font-semibold ring-1 ring-line">Try again</button>
            </Card>
          )}

          {step === "done" && result && (
            <Card className="p-5" accent="border-l-good">
              <h3 className="font-serif text-xl font-semibold text-navy">Ready for your review</h3>
              <p className="mt-2 text-sm text-ink-soft">
                <strong className="text-ink">{countItems(result.plan.newCounts)} items</strong> are waiting: {describeBatch(result.plan.newCounts).join(", ") || "no new items"}.
              </p>
              {result.warnings.length > 0 && (
                <p className="mt-2 text-xs text-ink-muted">{result.warnings.length} import note{result.warnings.length === 1 ? "" : "s"} recorded for unsupported or incomplete resources.</p>
              )}
              <p className="mt-2 text-sm text-ink-soft">Review the imported items, then confirm the ones that should be used for conflict checks and reminders.</p>
              <div className="mt-5 flex flex-wrap gap-2">
                <Link href="/passport/review/" className="inline-flex min-h-12 items-center rounded-full bg-brand-700 px-5 text-sm font-semibold text-white hover:bg-brand-800">Review and confirm</Link>
                <Link href="/passport/sources/" className="inline-flex min-h-12 items-center rounded-full px-5 text-sm font-semibold text-brand-700 ring-1 ring-line hover:bg-brand-50">See source details</Link>
              </div>
            </Card>
          )}
        </>
      )}

      <Disclaimer />
    </div>
  );
}
