import Link from "next/link";

const nodes = [
  { title: "Patient Passport", text: "patient-owned medications, allergies and confirmations", tone: "border-emerald-300 bg-emerald-50" },
  { title: "Clinical sources", text: "live SMART Health IT FHIR R4 sandbox plus scripted multi-EHR scenarios", tone: "border-blue-300 bg-blue-50" },
  { title: "Photon adapter", text: "dispense evidence and authorized provider handoff", tone: "border-cyan-300 bg-cyan-50" },
];

export default function SystemDesignPage() {
  return <div className="w-full space-y-6 pb-10">
    <header className="border border-slate-800 bg-slate-950 px-6 py-8 text-white sm:px-8"><p className="text-xs font-semibold uppercase tracking-[.18em] text-teal-300">System design</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.045em]">Evidence enters through bounded adapters.<br/>Authority never leaves the clinician.</h1><p className="mt-4 max-w-3xl text-sm leading-6 text-slate-300">This view documents the implemented prototype: data contracts, agent state, deterministic safety checks, policy boundaries, MCP access and human approval.</p></header>
    <section className="border border-slate-200 bg-white p-5 sm:p-7"><p className="text-[11px] font-semibold uppercase tracking-[.16em] text-teal-700">Context architecture</p><div className="mt-6 grid items-center gap-4 xl:grid-cols-[1fr_auto_1.2fr_auto_1fr]">
      <div className="space-y-3">{nodes.map((node) => <div key={node.title} className={`border-l-4 p-4 ${node.tone}`}><p className="font-semibold text-slate-950">{node.title}</p><p className="mt-1 text-xs leading-5 text-slate-600">{node.text}</p></div>)}</div><span className="hidden text-2xl text-teal-700 xl:block">→</span>
      <div className="border-2 border-teal-600 bg-teal-50 p-5"><p className="text-lg font-semibold text-slate-950">Parthia clinician runtime</p><div className="mt-4 grid grid-cols-2 gap-2 text-xs">{["case builder", "source validation", "Rx normalization", "rule engine", "agent state machine", "policy gate", "audit trace", "report builder"].map((name) => <span key={name} className="border border-teal-200 bg-white px-3 py-2 text-slate-700">{name}</span>)}</div></div><span className="hidden text-2xl text-teal-700 xl:block">→</span>
      <div className="space-y-3">{[{title:"Clinician workspace",text:"review findings, inspect sources and record decisions"},{title:"Interactive 3D atlas",text:"maps warning context to body systems without claiming diagnosis"},{title:"Agent chat",text:"grounded questions with visible tools and refusals"},{title:"MCP server + report",text:"14 bounded tools and portable decision evidence"}].map((node) => <div key={node.title} className="border-l-4 border-slate-400 bg-slate-50 p-4"><p className="font-semibold text-slate-950">{node.title}</p><p className="mt-1 text-xs leading-5 text-slate-600">{node.text}</p></div>)}</div>
    </div></section>
    <section className="grid gap-5 lg:grid-cols-3">{[{n:"01",title:"Deterministic detection",text:"Versioned rules, not model prose, produce interaction, duplicate and status-conflict findings."},{n:"02",title:"Provenance preserved",text:"Normalization groups records but never erases how each source represented the medication."},{n:"03",title:"Human-gated writes",text:"The policy layer blocks medication changes and opens provider workflows only after approval."}].map((item) => <article key={item.n} className="border border-slate-200 bg-white p-5"><span className="text-xs font-semibold text-teal-700">{item.n}</span><h2 className="mt-5 text-xl font-semibold text-slate-950">{item.title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{item.text}</p></article>)}</section>
    <section className="border border-slate-200 bg-white"><div className="border-b border-slate-200 p-5"><p className="text-[11px] font-semibold uppercase tracking-[.16em] text-teal-700">Execution sequence</p></div><div className="grid gap-px bg-slate-200 md:grid-cols-4">{["Fetch + validate sources","Normalize + retain provenance","Check + explain findings","Clarify + route for review"].map((step, i) => <div key={step} className="bg-white p-5"><span className="text-xs font-semibold text-slate-400">0{i+1}</span><p className="mt-3 text-sm font-semibold text-slate-900">{step}</p></div>)}</div></section>
    <div className="flex flex-wrap gap-3"><Link href="/clinician/" className="bg-teal-700 px-5 py-2.5 text-sm font-semibold text-white">Open workspace</Link><Link href="/clinician/presentation/" className="border border-slate-300 bg-white px-5 py-2.5 text-sm font-semibold text-slate-800">Open presentation</Link><Link href="/clinician/eval/" className="border border-slate-300 bg-white px-5 py-2.5 text-sm font-semibold text-slate-800">View evaluation</Link></div>
  </div>;
}
