"use client";

import Link from "next/link";
import { useCallback, useEffect, useRef, useState, type ReactNode } from "react";
import { SystemDiagram } from "@/components/architecture/SystemDiagram";
import { RULES } from "@/lib/safetyEngine";

type Slide = { label: string; eyebrow: string; title: ReactNode; body: ReactNode };

const slides: Slide[] = [
  { label: "Opening", eyebrow: "HACKERS & HEALERS · MEDICATION SAFETY", title: <>Five medication records.<br/><span className="text-teal-300">No shared truth.</span></>, body: <><p className="max-w-3xl text-xl leading-8 text-slate-300">Parthia turns fragmented EHR, pharmacy and patient-reported medication data into one source-backed clinician review queue.</p><div className="mt-10 grid max-w-3xl grid-cols-3 border border-slate-700"><Metric value="5" label="evidence sources"/><Metric value="8" label="bounded agent stages"/><Metric value="0" label="autonomous care changes"/></div><p className="mt-8 max-w-3xl border-l-2 border-amber-300 pl-4 text-base italic leading-7 text-amber-100">A presentation, at a hackathon that said no presentations. Relax, organizers: it is not for you. It is for the investors.</p></> },
  { label: "Problem", eyebrow: "01 · THE FRAGMENTATION GAP", title: "Every chart can look safe on its own", body: <div className="mt-10 grid gap-px overflow-hidden bg-slate-700 md:grid-cols-3"><Story index="01" title="Hospital EHR" text="Warfarin is active, but the chart cannot see what urgent care prescribed."/><Story index="02" title="Urgent care" text="Ciprofloxacin is active, but the prescriber cannot see the full medication context."/><Story index="03" title="Patient report" text="Ibuprofen never reached either chart, yet it changes the risk picture."/></div> },
  { label: "Agent", eyebrow: "02 · BOUNDED AUTONOMY", title: "The agent assembles evidence; people retain authority", body: <div className="mt-10 grid items-center gap-4 lg:grid-cols-[1fr_auto_1fr_auto_1fr]"><Flow title="Gather" text="FHIR-shaped EHR, pharmacy and patient records"/><Arrow/><Flow title="Reason" text="Normalize, reconcile and run deterministic checks"/><Arrow/><Flow title="Route" text="Explain evidence and stop at the clinician gate"/></div> },
  { label: "Demo", eyebrow: "03 · THE DEMO MOMENT", title: "A risk appears only after the records converge", body: <div className="mt-10 grid gap-5 lg:grid-cols-3"><div className="border border-slate-700 p-6"><p className="text-xs font-semibold uppercase tracking-[.16em] text-slate-400">Before</p><p className="mt-3 text-2xl font-semibold">Five disconnected lists</p><p className="mt-3 leading-7 text-slate-300">Brand names, inconsistent status, stale data and a patient-reported OTC medication.</p></div><div className="border-l-4 border-red-500 bg-red-500/10 p-6"><p className="text-xs font-semibold uppercase tracking-[.16em] text-red-300">After reconciliation</p><p className="mt-3 text-2xl font-semibold">Warfarin + ibuprofen requires review</p><p className="mt-3 leading-7 text-slate-300">The finding retains every source and cites label evidence.</p></div><div className="border-l-4 border-teal-300 bg-teal-300/10 p-6"><p className="text-xs font-semibold uppercase tracking-[.16em] text-teal-300">Body atlas</p><p className="mt-3 text-2xl font-semibold">Risk context becomes visible</p><p className="mt-3 leading-7 text-slate-300">The interactive 3D model highlights circulatory and gastrointestinal context, not a diagnosis.</p></div></div> },
  { label: "Architecture", eyebrow: "04 · SYSTEM ARCHITECTURE", title: "Five stages, one flow", body: <SystemDiagram ruleCount={RULES.length} tone="dark" className="mt-6" /> },
  { label: "Trust", eyebrow: "05 · SAFETY MODEL", title: "The model cannot invent clinical authority", body: <div className="mt-8 space-y-3">{[["01","Rules own detection","Interaction and conflict findings come from versioned deterministic policies."],["02","Evidence stays attached","Every normalized medication retains its original record and source."],["03","Write tools are gated","Medication change requests are blocked until an authorized clinician decides."],["04","Uncertainty is a result","Missing and unavailable sources produce an incomplete case, not false confidence."]].map(([n,t,d]) => <div key={n} className="grid grid-cols-[48px_220px_1fr] items-center border-b border-slate-700 py-4"><span className="text-teal-300">{n}</span><b>{t}</b><span className="text-slate-300">{d}</span></div>)}</div> },
  { label: "Proof", eyebrow: "06 · WHAT EXISTS TODAY", title: "A working prototype with observable behavior", body: <div className="mt-10 grid gap-4 md:grid-cols-4"><Metric value="6" label="demonstration patient cases"/><Metric value="12/12" label="prototype eval cases"/><Metric value="224" label="automated tests"/><Metric value="14" label="MCP tools"/></div> },
  { label: "Close", eyebrow: "PARTHIA HEALTH", title: <>Medication safety across the gaps<br/><span className="text-teal-300">between systems.</span></>, body: <><p className="mt-8 max-w-3xl text-xl leading-8 text-slate-300">One patient-owned passport. One bounded clinician agent. One review trail that shows exactly what happened and who decided.</p><Link href="/clinician/" className="mt-10 inline-flex bg-teal-400 px-6 py-3 text-sm font-semibold text-slate-950">Open the live workspace</Link></> },
];

function Metric({ value, label }: { value: string; label: string }) { return <div className="border-r border-slate-700 px-6 py-5 last:border-0"><p className="text-3xl font-semibold text-white">{value}</p><p className="mt-1 text-xs uppercase tracking-[.14em] text-slate-400">{label}</p></div>; }
function Story({ index, title, text }: { index: string; title: string; text: string }) { return <div className="bg-slate-900 p-6"><p className="text-xs font-semibold text-teal-300">{index}</p><h3 className="mt-5 text-xl font-semibold">{title}</h3><p className="mt-3 leading-7 text-slate-300">{text}</p></div>; }
function Flow({ title, text }: { title: string; text: string }) { return <div className="border border-slate-700 p-6"><p className="text-lg font-semibold">{title}</p><p className="mt-2 text-sm leading-6 text-slate-300">{text}</p></div>; }
function Arrow() { return <span className="hidden text-2xl text-teal-300 lg:block">→</span>; }

export function ClinicianPresentation() {
  const [index, setIndex] = useState(0);
  const [fullscreen, setFullscreen] = useState(false);
  const shell = useRef<HTMLDivElement>(null);
  const go = useCallback((next: number) => setIndex(Math.max(0, Math.min(slides.length - 1, next))), []);
  const toggle = useCallback(() => document.fullscreenElement ? void document.exitFullscreen() : void shell.current?.requestFullscreen(), []);
  useEffect(() => {
    const key = (event: KeyboardEvent) => { if (["ArrowRight", "PageDown", " "].includes(event.key)) { event.preventDefault(); setIndex((value) => Math.min(slides.length - 1, value + 1)); } if (["ArrowLeft", "PageUp"].includes(event.key)) { event.preventDefault(); setIndex((value) => Math.max(0, value - 1)); } if (event.key.toLowerCase() === "f") toggle(); };
    const full = () => setFullscreen(Boolean(document.fullscreenElement));
    window.addEventListener("keydown", key); document.addEventListener("fullscreenchange", full);
    return () => { window.removeEventListener("keydown", key); document.removeEventListener("fullscreenchange", full); };
  }, [toggle]);
  const slide = slides[index]!;
  return <div ref={shell} className={`flex min-h-[calc(100vh-8rem)] flex-col bg-slate-950 text-white ${fullscreen ? "min-h-screen" : ""}`}>
    <div className="flex items-center justify-between border-b border-slate-800 px-5 py-3 text-xs text-slate-400"><span>{String(index + 1).padStart(2,"0")} / {String(slides.length).padStart(2,"0")} · {slide.label}</span><button type="button" onClick={toggle} className="border border-slate-700 px-3 py-1.5 text-white">{fullscreen ? "Exit fullscreen" : "Present fullscreen"}</button></div>
    <article className="mx-auto flex w-full max-w-[1440px] flex-1 flex-col justify-center px-6 py-12 sm:px-12 lg:px-20"><p className="text-xs font-semibold uppercase tracking-[.2em] text-teal-300">{slide.eyebrow}</p><h1 className="mt-5 max-w-6xl text-4xl font-semibold leading-[1.05] tracking-[-.05em] sm:text-6xl lg:text-7xl">{slide.title}</h1><div className="mt-4">{slide.body}</div></article>
    <div className="flex items-center justify-between border-t border-slate-800 px-5 py-3"><button type="button" disabled={index === 0} onClick={() => go(index - 1)} className="px-3 py-2 text-sm disabled:opacity-30">← Previous</button><div className="flex gap-2">{slides.map((item, i) => <button type="button" key={item.label} aria-label={`Open ${item.label} slide`} onClick={() => go(i)} className={`h-1.5 w-4 sm:w-7 ${i === index ? "bg-teal-300" : "bg-slate-700"}`} />)}</div><button type="button" disabled={index === slides.length - 1} onClick={() => go(index + 1)} className="px-3 py-2 text-sm disabled:opacity-30">Next →</button></div>
  </div>;
}
