import type { PhotonScreenAlert } from "./photonScreen";
/**
 * Responses captured from the Photon Neutron sandbox, keyed by treatment key.
 *
 * GENERATED by `npx tsx --env-file=.env.local scripts/photon-live-check.mts`.
 * Do not hand-edit: a capture only belongs here if the sandbox really returned
 * it, because the UI labels anything in this map "Recorded sandbox response".
 */
export interface RecordedPhotonScreen {
  recordedAt: string;
  treatmentKey: string;
  alerts: PhotonScreenAlert[];
}
export const PHOTON_RECORDED_SCREENS: Record<string, RecordedPhotonScreen> = {
  "ciprofloxacin-500-mg": {
    "recordedAt": "2026-10-03T15:28:08.927Z",
    "treatmentKey": "ciprofloxacin-500-mg",
    "alerts": [
      {
        "type": "DRUG",
        "severity": "MODERATE",
        "description": "Fluoroquinolones such as Ciprofloxacin HCl Oral Tablet 500 MG may increase anticoagulant effects of Warfarin Sodium Oral Tablet 5 MG.",
        "involvedEntities": [
          {
            "id": "med_01JVT1WGAMK8H6M0KRPYTQ989A",
            "name": "Ciprofloxacin HCl",
            "kind": "drafted"
          },
          {
            "id": "mht_01M412P6TR3EEHFTW7N6AFRQ7Z",
            "name": "Warfarin Sodium",
            "kind": "existing"
          }
        ]
      }
    ]
  },
  "amoxicillin-500-mg": {
    "recordedAt": "2026-10-03T15:28:09.988Z",
    "treatmentKey": "amoxicillin-500-mg",
    "alerts": [
      {
        "type": "DRUG",
        "severity": "MODERATE",
        "description": "Penicillins, such as Amoxicillin Oral Capsule 500 MG, may increase anticoagulant effects of Vitamin K Antagonists, such as Warfarin Sodium Oral Tablet 5 MG.",
        "involvedEntities": [
          {
            "id": "med_01KAY4KR7NRMWJWPDV7J8Z994G",
            "name": "Amoxicillin",
            "kind": "drafted"
          },
          {
            "id": "mht_01M412P6TR3EEHFTW7N6AFRQ7Z",
            "name": "Warfarin Sodium",
            "kind": "existing"
          }
        ]
      },
      {
        "type": "ALLERGEN",
        "severity": "MODERATE",
        "description": "The use of Amoxicillin Oral Capsule 500 MG may result in an allergic reaction based on a reported history of allergy to penicillin G.",
        "involvedEntities": [
          {
            "id": "alg_01GBAPSGF62Q3WBET1QD2J3F0F",
            "name": "penicillin G",
            "kind": "allergen"
          },
          {
            "id": "med_01KAY4KR7NRMWJWPDV7J8Z994G",
            "name": "Amoxicillin",
            "kind": "drafted"
          }
        ]
      }
    ]
  },
  "ibuprofen-200-mg": {
    "recordedAt": "2026-10-03T15:28:10.664Z",
    "treatmentKey": "ibuprofen-200-mg",
    "alerts": [
      {
        "type": "DRUG",
        "severity": "MAJOR",
        "description": "Non-selective nonsteroidal anti-inflammatory agents (eg, Ibuprofen Oral Capsule 200 MG) may diminish the cardioprotective effect of aspirin. Non-selective nonsteroidal anti-inflammatory agents (eg, Ibuprofen Oral Capsule 200 MG) may enhance the adverse/toxic effect of aspirin. An increased risk of bleeding may be associated with use of this combination. Aspirin may decrease the serum concentration of non-selective nonsteroidal anti-inflammatory agents (eg, Ibuprofen Oral Capsule 200 MG).",
        "involvedEntities": [
          {
            "id": "mht_01M412P6VFP47NJ16RG4PQ1E8S",
            "name": "Aspirin 81",
            "kind": "existing"
          },
          {
            "id": "med_01KZEG3HFJQF4VK0AXCYAVS77J",
            "name": "Ibuprofen",
            "kind": "drafted"
          }
        ]
      },
      {
        "type": "DRUG",
        "severity": "MODERATE",
        "description": "Nonselective nonsteroidal anti-inflammatory agents (eg, Ibuprofen Oral Capsule 200 MG) may enhance the anticoagulant effect of vitamin K antagonists (eg, Warfarin Sodium Oral Tablet 5 MG).",
        "involvedEntities": [
          {
            "id": "med_01KZEG3HFJQF4VK0AXCYAVS77J",
            "name": "Ibuprofen",
            "kind": "drafted"
          },
          {
            "id": "mht_01M412P6TR3EEHFTW7N6AFRQ7Z",
            "name": "Warfarin Sodium",
            "kind": "existing"
          }
        ]
      },
      {
        "type": "DRUG",
        "severity": "MODERATE",
        "description": "Ibuprofen Oral Capsule 200 MG may impair the hypotensive effect of Metoprolol Succinate ER Oral Tablet Extended Release 24 Hour 50 MG.",
        "involvedEntities": [
          {
            "id": "med_01KZEG3HFJQF4VK0AXCYAVS77J",
            "name": "Ibuprofen",
            "kind": "drafted"
          },
          {
            "id": "mht_01M412P6V5WH60RXK62HGV7T7W",
            "name": "Metoprolol Succinate ER",
            "kind": "existing"
          }
        ]
      },
      {
        "type": "ALLERGEN",
        "severity": "MODERATE",
        "description": "The use of Ibuprofen Oral Capsule 200 MG may result in an allergic reaction based on a reported history of allergy to ibuprofen.",
        "involvedEntities": [
          {
            "id": "alg_01GBAPSGE2TV2JSWR3BAYPP15E",
            "name": "ibuprofen",
            "kind": "allergen"
          },
          {
            "id": "med_01KZEG3HFJQF4VK0AXCYAVS77J",
            "name": "Ibuprofen",
            "kind": "drafted"
          }
        ]
      }
    ]
  },
};
