/**
 * Live check of the Photon Neutron sandbox against the three demo drafts.
 *
 * `next dev` does not serve the root `api/` functions, so this imports the
 * handlers directly and calls them the way Vercel would. It writes one
 * recorded response per demo draft into `fixtures/photon/` with its timestamp.
 *
 * Run with: npx tsx --env-file=.env.local scripts/photon-live-check.mts
 * Credentials are read from the environment and never printed.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { PHOTON_DEMO_DRAFTS, photonTreatment, photonTreatmentId } from "../src/lib/clinician/photonCatalog";
// The api/ handlers are CommonJS from this .mts entry point, so the default
// export is taken off the module namespace rather than imported directly.
const { default: syncHandler } = await import("../api/photon/sync-patient");
const { default: screenHandler } = await import("../api/photon/screen");
interface Captured { code: number; body: unknown }
function collector() {
  const captured: Captured = { code: 0, body: null };
  const response = {
    status(code: number) { captured.code = code; return response; },
    json(body: unknown) { captured.body = body; },
    setHeader() {},
  };
  return { response, captured };
}
async function callSync(): Promise<Captured> {
  const { response, captured } = collector();
  await syncHandler({ method: "POST" }, response);
  return captured;
}
async function callScreen(treatmentIds: string[]): Promise<Captured> {
  const { response, captured } = collector();
  await screenHandler({ method: "POST", body: { treatmentIds } }, response);
  return captured;
}
const fixtureDir = join(process.cwd(), "fixtures", "photon");
mkdirSync(fixtureDir, { recursive: true });
console.log("== sync-patient, call 1 ==");
const first = await callSync();
console.log(JSON.stringify(first, null, 2));
console.log("== sync-patient, call 2 (idempotency) ==");
const second = await callSync();
console.log(JSON.stringify(second, null, 2));
const firstId = (first.body as { patientId?: string } | null)?.patientId;
const secondId = (second.body as { patientId?: string } | null)?.patientId;
console.log(`idempotent: ${Boolean(firstId) && firstId === secondId ? "YES" : "NO"} (${firstId ?? "none"} / ${secondId ?? "none"})`);
interface Capture {
  recordedAt: string;
  treatmentKey: string;
  alerts: { type: string; severity: string; description: string; involvedEntities: { id: string; name: string; kind: string }[] }[];
}
const captures: Capture[] = [];
let failures = 0;
for (const draft of PHOTON_DEMO_DRAFTS) {
  const treatment = photonTreatment(draft.treatmentKey);
  console.log(`\n== screen draft: ${draft.label} (expects ${draft.expects}) ==`);
  const result = await callScreen([photonTreatmentId(draft.treatmentKey)]);
  console.log("status", result.code);
  const body = result.body as { alerts?: Capture["alerts"]; screenedAt?: string; patientId?: string; error?: string; detail?: string };
  if (result.code !== 200) {
    failures++;
    console.log("FAILED:", body.error ?? "unknown error", "|", body.detail ?? "");
    continue;
  }
  for (const alert of body.alerts ?? []) {
    console.log(`  [${alert.type} / ${alert.severity}] ${alert.description}`);
    console.log(`    involves: ${alert.involvedEntities.map((entity) => `${entity.name} (${entity.kind})`).join(", ")}`);
  }
  if (!(body.alerts ?? []).length) {
    failures++;
    console.log("  NO ALERTS RETURNED");
    continue;
  }
  const capture: Capture = { recordedAt: body.screenedAt ?? new Date().toISOString(), treatmentKey: draft.treatmentKey, alerts: body.alerts ?? [] };
  captures.push(capture);
  writeFileSync(join(fixtureDir, `${draft.treatmentKey}-screen.json`), `${JSON.stringify({
    ...capture,
    draft: { treatmentId: treatment?.id, name: treatment?.name, label: draft.label },
    expects: draft.expects,
    patientId: body.patientId,
    source: "Photon Neutron sandbox",
    live: false,
    label: "Recorded sandbox response",
    note: "Real sandbox response captured for the offline fallback. Synthetic patient. No credentials or tokens are stored here.",
  }, null, 2)}\n`);
}
if (captures.length) {
  const entries = captures.map((capture) => `  ${JSON.stringify(capture.treatmentKey)}: ${JSON.stringify(capture, null, 2).split("\n").join("\n  ")},`).join("\n");
  writeFileSync(join(process.cwd(), "src", "lib", "clinician", "photonRecorded.ts"), `import type { PhotonScreenAlert } from "./photonScreen";
/**
 * Responses captured from the Photon Neutron sandbox, keyed by treatment key.
 *
 * GENERATED by \`npx tsx --env-file=.env.local scripts/photon-live-check.mts\`.
 * Do not hand-edit: a capture only belongs here if the sandbox really returned
 * it, because the UI labels anything in this map "Recorded sandbox response".
 */
export interface RecordedPhotonScreen {
  recordedAt: string;
  treatmentKey: string;
  alerts: PhotonScreenAlert[];
}
export const PHOTON_RECORDED_SCREENS: Record<string, RecordedPhotonScreen> = {
${entries}
};
`);
  console.log(`\ncaptured ${captures.length} real response(s) into fixtures/photon/ and src/lib/clinician/photonRecorded.ts`);
} else {
  console.log("\nno real response captured, so fixtures/photon/ and photonRecorded.ts are left alone");
}
console.log(failures ? `DEMO CHECKS INCOMPLETE: ${failures} of ${PHOTON_DEMO_DRAFTS.length} draft(s) did not return alerts` : "DEMO CHECKS: all three drafts returned alerts");
