import type { Medication, PatientId, PatientRecord } from "../types";
import { importForReview, recordActivity, saveConnection } from "../passport/actions";
import { countItems, planImport, type ImportPlan } from "../passport/importPlan";
import { passportStore, type PassportStore } from "../passport/store";
import { lookupDrug, lookupRxcui } from "../terminology/medications";
import { mappedCollections } from "./importer";
import { mapBundle } from "./mapper";
import type { FhirBundle, FhirResource } from "./types";

/**
 * LIVE PUBLIC FHIR IMPORT
 *
 * Reads from the SMART Health IT public FHIR R4 sandbox. The server is real and
 * the request really does leave this device. The patients on it are synthetic
 * records generated by Synthea, not real people, and this is not a connection
 * to Epic, Oracle Health or any other live health system.
 *
 * Parthia is a static export with no server of its own, so everything here runs
 * in the browser. Both APIs used allow browser (CORS) calls:
 *   - https://r4.smarthealthit.org    FHIR R4, read-only
 *   - https://rxnav.nlm.nih.gov/REST  RxNorm ingredient lookup
 *
 * Medicines are mapped with Parthia's own dictionary first, so the live source
 * behaves like every other source. Only what the dictionary does not recognise
 * goes to RxNav, and whatever RxNav resolves is labelled on the item so a live
 * lookup is never mistaken for a curated mapping.
 *
 * Imported items land in Review, unconfirmed, like every other source.
 */

export const SANDBOX_BASE = "https://r4.smarthealthit.org";
export const RXNAV_BASE = "https://rxnav.nlm.nih.gov/REST";

/** Shown on items, in Review and on the Sources screen. */
export const LIVE_SOURCE_LABEL = "Public FHIR sandbox (live)";
export const LIVE_SOURCE_ID = "fhir-sandbox-live";

/** Recorded on any item whose ingredient came from the live RxNav API. */
export const RXNAV_PROVENANCE = "ingredient via RxNav (live)";

/** What the patient reads when the public sandbox does not answer. */
export const SANDBOX_UNAVAILABLE =
  "The public FHIR sandbox did not answer, so nothing was imported. It is a free shared server and is sometimes busy or offline. Nothing in your Passport changed, and you can try again in a moment.";

/* ---- Reading JSON from two public APIs ----------------------------------- */

/** Injectable so tests never touch the network. */
export type FetchLike = (url: string, init?: RequestInit) => Promise<Response>;

type Json = Record<string, unknown>;

function obj(value: unknown): Json | undefined {
  return typeof value === "object" && value !== null && !Array.isArray(value) ? (value as Json) : undefined;
}
function arr(value: unknown): unknown[] {
  return Array.isArray(value) ? value : [];
}
function str(value: unknown): string | undefined {
  return typeof value === "string" && value.length > 0 ? value : undefined;
}

/**
 * GET one JSON document, or null if it could not be read.
 *
 * The FHIR server is happy with the FHIR media type. RxNav is NOT: it answers
 * 406 Not Acceptable for `application/fhir+json`, so RxNav calls ask for plain
 * JSON. This is the one detail that breaks the whole import if it is wrong.
 */
export async function getJson(url: string, fetchImpl: FetchLike = fetch): Promise<unknown | null> {
  try {
    const accept = url.startsWith(RXNAV_BASE) ? "application/json" : "application/fhir+json";
    const res = await fetchImpl(url, { headers: { Accept: accept } });
    if (!res.ok) return null;
    return (await res.json()) as unknown;
  } catch {
    return null; // offline, blocked, CORS, or malformed JSON: the caller degrades to a message
  }
}

/* ---- Who is on the sandbox ----------------------------------------------- */

export interface SandboxPatient {
  id: string;
  name: string;
  birthDate?: string;
  /** How many active MedicationRequest resources the server holds for them. */
  activeMedications: number;
}

/** Synthea appends digits to names ("Aaron697 Barrows492"); strip them for display. */
function displayName(patient: Json, fallback: string): string {
  const name = obj(arr(patient.name)[0]);
  const given = arr(name?.given)
    .map((g) => str(g))
    .filter(Boolean)
    .join(" ");
  const cleaned = [given, str(name?.family)]
    .filter(Boolean)
    .join(" ")
    .replace(/\d+/g, "")
    .replace(/\s+/g, " ")
    .trim();
  return cleaned || str(name?.text) || fallback;
}

function resourcesOf(bundle: unknown, resourceType: string): Json[] {
  return arr(obj(bundle)?.entry)
    .map((e) => obj(obj(e)?.resource))
    .filter((r): r is Json => !!r && r.resourceType === resourceType);
}

/**
 * Sandbox patients who have active prescriptions, busiest first. Counting by
 * subject on one search keeps this to two requests.
 */
export async function listSandboxPatients(limit = 8, fetchImpl: FetchLike = fetch): Promise<SandboxPatient[]> {
  const search = await getJson(`${SANDBOX_BASE}/MedicationRequest?status=active&_count=200&_elements=subject`, fetchImpl);
  if (!obj(search)) throw new Error(SANDBOX_UNAVAILABLE);
  const counts = new Map<string, number>();
  for (const entry of arr(obj(search)?.entry)) {
    const ref = str(obj(obj(obj(entry)?.resource)?.subject)?.reference);
    if (!ref?.startsWith("Patient/")) continue;
    const id = ref.slice("Patient/".length);
    counts.set(id, (counts.get(id) ?? 0) + 1);
  }
  const ids = [...counts.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, limit)
    .map(([id]) => id);
  if (!ids.length) return [];
  const patients = await getJson(`${SANDBOX_BASE}/Patient?_id=${ids.join(",")}&_count=${ids.length}`, fetchImpl);
  if (!obj(patients)) throw new Error(SANDBOX_UNAVAILABLE);
  return resourcesOf(patients, "Patient")
    .map((p) => {
      const id = str(p.id) ?? "";
      return { id, name: displayName(p, id), birthDate: str(p.birthDate), activeMedications: counts.get(id) ?? 0 };
    })
    .filter((p) => p.id)
    .sort((a, b) => b.activeMedications - a.activeMedications);
}

/* ---- One patient's record as a Bundle the existing mapper understands ---- */

/**
 * The sandbox names medicines three ways: a CodeableConcept with text, a
 * CodeableConcept with only a coding display, or a Medication reference with a
 * display and no code at all. Parthia's mapper reads
 * `medicationCodeableConcept.text`, so fill that in from whatever the server
 * gave us; a request with no name anywhere is dropped rather than imported as
 * a blank medicine.
 */
function withMedicationName(resource: Json): Json | null {
  const cc = obj(resource.medicationCodeableConcept);
  const codingDisplay = arr(cc?.coding)
    .map((c) => str(obj(c)?.display))
    .find(Boolean);
  const text = str(cc?.text) ?? codingDisplay ?? str(obj(resource.medicationReference)?.display);
  if (!text) return null;
  return { ...resource, medicationCodeableConcept: { ...(cc ?? {}), text } };
}

/** Patient, MedicationRequest and Condition for one sandbox patient, as a FHIR collection Bundle. */
export async function fetchSandboxBundle(sandboxPatientId: string, fetchImpl: FetchLike = fetch): Promise<FhirBundle> {
  const id = encodeURIComponent(sandboxPatientId);
  const [patient, meds, conditions] = await Promise.all([
    getJson(`${SANDBOX_BASE}/Patient/${id}`, fetchImpl),
    getJson(`${SANDBOX_BASE}/MedicationRequest?patient=${id}&_count=50`, fetchImpl),
    getJson(`${SANDBOX_BASE}/Condition?patient=${id}&_count=50`, fetchImpl),
  ]);
  const person = obj(patient);
  if (!person || person.resourceType !== "Patient") throw new Error(SANDBOX_UNAVAILABLE);
  const named = resourcesOf(meds, "MedicationRequest")
    .map(withMedicationName)
    .filter((r): r is Json => r !== null);
  const resources = [person, ...named, ...resourcesOf(conditions, "Condition")];
  return {
    resourceType: "Bundle",
    type: "collection",
    entry: resources.map((resource) => ({ resource: resource as unknown as FhirResource })),
  };
}

/* ---- Ingredient mapping: dictionary first, then live RxNav --------------- */

export type MappingMethod =
  /** Parthia's curated dictionary recognised it; no network call was made. */
  | "dictionary"
  /** RxNav resolved the product RxCUI to its ingredient. */
  | "rxnav-code"
  /** All the server gave was text, so RxNav matched on the name. */
  | "rxnav-text"
  /** Neither the dictionary nor RxNav could name an ingredient. */
  | "unmapped";

export interface IngredientMapping {
  method: MappingMethod;
  /** Lower-case ingredient name, the key the rest of Parthia matches on. */
  generic?: string;
  rxcui?: string;
  /** The product has more than one ingredient; the first one is used. */
  combination: boolean;
  ingredientCount: number;
}

const UNMAPPED: IngredientMapping = { method: "unmapped", combination: false, ingredientCount: 0 };

/**
 * Name the ingredient behind one prescription. The curated dictionary is tried
 * first so the live source maps the same medicine the same way as every other
 * source; RxNav is only asked about what is left over.
 */
export async function resolveIngredient(
  input: { rxcui?: string; text?: string },
  fetchImpl: FetchLike = fetch,
): Promise<IngredientMapping> {
  const curated = (input.rxcui ? lookupRxcui(input.rxcui) : undefined) ?? (input.text ? lookupDrug(input.text) : undefined);
  if (curated) return { method: "dictionary", generic: curated.generic, rxcui: curated.rxcui, combination: false, ingredientCount: 1 };

  let rxcui = input.rxcui;
  let method: MappingMethod = "rxnav-code";
  if (!rxcui) {
    if (!input.text) return UNMAPPED;
    const approximate = await getJson(`${RXNAV_BASE}/approximateTerm.json?term=${encodeURIComponent(input.text)}&maxEntries=1`, fetchImpl);
    rxcui = str(obj(arr(obj(obj(approximate)?.approximateGroup)?.candidate)[0])?.rxcui);
    method = "rxnav-text";
    if (!rxcui) return UNMAPPED;
  }

  const related = await getJson(`${RXNAV_BASE}/rxcui/${encodeURIComponent(rxcui)}/related.json?tty=IN`, fetchImpl);
  const ingredients = arr(obj(obj(related)?.relatedGroup)?.conceptGroup)
    .flatMap((group) => arr(obj(group)?.conceptProperties))
    .map((c) => obj(c))
    .filter((c): c is Json => !!str(c?.name));
  const first = ingredients[0];
  if (!first) return UNMAPPED;
  return {
    method,
    generic: str(first.name)!.toLowerCase(),
    rxcui: str(first.rxcui),
    combination: ingredients.length > 1,
    ingredientCount: ingredients.length,
  };
}

/**
 * The provenance line kept on the item and shown in Review, so the patient and
 * any clinician can see the medicine name as the server wrote it and how the
 * ingredient was found.
 */
export function liveProvenance(originalText: string, mapping: IngredientMapping): string {
  const parts = [originalText];
  if (mapping.combination) parts.push(`combination product, imported as the first of its ${mapping.ingredientCount} ingredients`);
  const how = mapping.method === "rxnav-text" ? `${RXNAV_PROVENANCE}, matched by name` : RXNAV_PROVENANCE;
  parts.push(`${mapping.generic}: ${how}`);
  return parts.join(" · ");
}

export interface LiveMappingCounts {
  dictionary: number;
  rxnav: number;
  unmapped: number;
  combinations: number;
}

/**
 * Re-map the medicines the dictionary did not recognise, using live RxNav.
 * Lookups run one at a time and repeated products are cached, to stay a polite
 * caller on a free public API.
 */
export async function enrichLiveMedications(
  medications: Medication[],
  fetchImpl: FetchLike = fetch,
): Promise<{ medications: Medication[]; counts: LiveMappingCounts }> {
  const counts: LiveMappingCounts = { dictionary: 0, rxnav: 0, unmapped: 0, combinations: 0 };
  const cache = new Map<string, IngredientMapping>();
  const out: Medication[] = [];
  for (const med of medications) {
    const originalText = med.source.originalText ?? med.name;
    const key = `${med.rxNormCode ?? ""}|${originalText.toLowerCase()}`;
    const mapping = cache.get(key) ?? (await resolveIngredient({ rxcui: med.rxNormCode, text: originalText }, fetchImpl));
    cache.set(key, mapping);
    if (mapping.method === "dictionary") {
      counts.dictionary++;
      out.push(med);
      continue;
    }
    if (!mapping.generic) {
      counts.unmapped++;
      out.push(med);
      continue;
    }
    counts.rxnav++;
    if (mapping.combination) counts.combinations++;
    out.push({
      ...med,
      name: mapping.combination && !/\(combination\)$/.test(med.name) ? `${med.name} (combination)` : med.name,
      genericName: mapping.generic,
      rxNormCode: mapping.rxcui ?? med.rxNormCode,
      source: { ...med.source, originalText: liveProvenance(originalText, mapping) },
    });
  }
  return { medications: out, counts };
}

/* ---- The import ---------------------------------------------------------- */

export interface LiveImportResult {
  plan: ImportPlan;
  /** Resources the mapper saw but does not keep in the Passport. */
  warnings: string[];
  counts: LiveMappingCounts;
  sandboxPatient: SandboxPatient;
}

/**
 * Fetch one sandbox patient, map it, name its ingredients and leave everything
 * waiting in Review. Nothing goes into the Passport itself: the patient decides
 * item by item, exactly as with a scanned document or a simulated EHR.
 *
 * The incoming name is deliberately NOT checked against the current patient.
 * A sandbox record always belongs to someone else, and the screen says so.
 */
export async function runLiveSandboxImport(
  sandboxPatient: SandboxPatient,
  patientId: PatientId,
  record: PatientRecord,
  fetchImpl: FetchLike = fetch,
  store: PassportStore = passportStore,
): Promise<LiveImportResult> {
  const bundle = await fetchSandboxBundle(sandboxPatient.id, fetchImpl);
  const importedAt = new Date().toISOString();
  const mapped = mapBundle(bundle, { patientId, sourceLabel: LIVE_SOURCE_LABEL, importedAt });
  const { medications, counts } = await enrichLiveMedications(mapped.medications, fetchImpl);
  const plan = planImport(mappedCollections({ ...mapped, medications }), record);
  await importForReview(patientId, plan.batch, "ehr", `${LIVE_SOURCE_LABEL}, sandbox patient ${sandboxPatient.name}`, store);
  // No snapshot: cross-source reconciliation compares a source against this
  // patient's own list, and a sandbox record is a different person entirely.
  await saveConnection(
    patientId,
    { id: LIVE_SOURCE_ID, kind: "ehr", name: LIVE_SOURCE_LABEL, status: "connected", simulated: false, connectedAt: importedAt, lastImportAt: importedAt },
    store,
  );
  const skipped = countItems(plan.duplicates);
  if (skipped) {
    await recordActivity(patientId, "import", `${skipped} item${skipped === 1 ? " was" : "s were"} already in your Passport and skipped`, "ehr", store);
  }
  return { plan, warnings: mapped.warnings, counts, sandboxPatient };
}
