"use client";

import Link from "next/link";
import { useState } from "react";
import { Card, Disclaimer } from "@/components/PageHeader";
import { fmtDate } from "@/components/passport/PassportChrome";
import { usePatient } from "@/lib/context/PatientContext";
import {
  LIVE_SOURCE_LABEL,
  RXNAV_PROVENANCE,
  SANDBOX_BASE,
  SANDBOX_UNAVAILABLE,
  listSandboxPatients,
  runLiveSandboxImport,
  type LiveImportResult,
  type SandboxPatient,
} from "@/lib/fhir/live";
import { countItems, describeBatch } from "@/lib/passport/importPlan";

/**
 * Import from the public SMART Health IT FHIR sandbox.
 *
 * Nothing is fetched until the patient asks for it, so no effect runs on mount
 * and no request leaves the device without a deliberate press.
 */
type Step = "about" | "listing" | "patients" | "importing" | "done" | "error";

const SANDBOX_HOST = new URL(SANDBOX_BASE).host;

/** The one thing a reader must not misunderstand: real server, synthetic people. */
function HonestyBanner() {
  return (
    <div className="rounded-xl border border-gold-200 bg-gold-50 px-4 py-3 text-sm text-[#5c430d]">
      <p className="font-semibold">A real server, with made-up patients.</p>
      <p className="mt-1">
        {SANDBOX_HOST} is a real, public FHIR R4 server. The patient records on it are synthetic, generated by Synthea, and belong to
        no real person. This is not a connection to Epic, to Oracle Health, or to any live health system, and none of your own
        information is sent anywhere.
      </p>
    </div>
  );
}

export default function FhirSandboxPage() {
  const { patientId, record } = usePatient();
  const [step, setStep] = useState<Step>("about");
  const [patients, setPatients] = useState<SandboxPatient[]>([]);
  const [result, setResult] = useState<LiveImportResult | null>(null);
  const [error, setError] = useState<string | null>(null);

  async function loadPatients() {
    setStep("listing");
    try {
      const found = await listSandboxPatients();
      if (!found.length) {
        setError("The sandbox answered, but it has no patients with active prescriptions right now. Nothing was imported.");
        setStep("error");
        return;
      }
      setPatients(found);
      setStep("patients");
    } catch (e) {
      setError(e instanceof Error ? e.message : SANDBOX_UNAVAILABLE);
      setStep("error");
    }
  }

  async function importPatient(sandboxPatient: SandboxPatient) {
    setStep("importing");
    try {
      setResult(await runLiveSandboxImport(sandboxPatient, patientId, record));
      setStep("done");
    } catch (e) {
      setError(e instanceof Error ? e.message : SANDBOX_UNAVAILABLE);
      setStep("error");
    }
  }

  return (
    <div className="mx-auto max-w-3xl space-y-5">
      <div>
        <Link href="/passport/add/" className="inline-flex min-h-11 items-center text-sm font-semibold text-brand-700 hover:text-brand-900">← Add to my Passport</Link>
        <h2 className="font-serif text-2xl font-semibold text-navy">{LIVE_SOURCE_LABEL}</h2>
        <p className="mt-1 text-sm text-ink-soft">Reads a synthetic patient record over FHIR R4 from {SANDBOX_HOST}, in this browser.</p>
        <p className="mt-2 text-xs font-medium text-brand-800">
          Your Passport stays on this device. Unlike every other source here, this page does send read-only requests out to a public
          server, and brings its answers back.
        </p>
      </div>
      <HonestyBanner />

      {step === "about" && (
        <Card className="p-5">
          <h3 className="font-serif text-xl font-semibold text-navy">What this does</h3>
          <ul className="mt-3 space-y-2 text-sm text-ink-soft">
            <li>
              <strong className="text-ink">Asks the sandbox who has prescriptions.</strong> A read-only FHIR search for active
              MedicationRequest resources, then the Patient records behind them.
            </li>
            <li>
              <strong className="text-ink">Imports one patient you pick.</strong> Patient, MedicationRequest and Condition. Nothing is
              written back to the server.
            </li>
            <li>
              <strong className="text-ink">Names each medicine&apos;s ingredient.</strong> Parthia&apos;s own medicine dictionary first. Anything it
              does not recognise is looked up live in RxNav, the US National Library of Medicine&apos;s RxNorm API, and the item is marked
              &ldquo;{RXNAV_PROVENANCE}&rdquo; so you can see which mapping came from where. A combination product is imported as its first
              ingredient and labelled a combination.
            </li>
            <li>
              <strong className="text-ink">Leaves everything in Review.</strong> Exactly like every other source. Nothing enters your
              Passport, or any analysis, until you confirm it item by item.
            </li>
          </ul>
          <p className="mt-4 text-sm text-ink-soft">
            Two requests leave this device when you continue: one to {SANDBOX_HOST} and one to rxnav.nlm.nih.gov. Both are public,
            read-only APIs. Your own Passport is not sent to either.
          </p>
          <p className="mt-2 text-sm text-ink-soft">
            The record you import belongs to a made-up person, not to {record.patient.name}, so treat it as demonstration data and
            discard it from Review when you are done looking.
          </p>
          <div className="mt-5 flex flex-wrap gap-2">
            <button type="button" onClick={() => void loadPatients()} className="min-h-12 rounded-full bg-brand-700 px-5 text-sm font-semibold text-white hover:bg-brand-800">
              List patients on the sandbox
            </button>
            <Link href="/passport/add/" className="inline-flex min-h-12 items-center rounded-full px-5 text-sm font-semibold text-ink-soft ring-1 ring-line hover:bg-cream-dark">Cancel</Link>
          </div>
        </Card>
      )}

      {(step === "listing" || step === "importing") && (
        <Card className="p-5">
          <p role="status" className="flex items-center gap-3 text-sm text-ink">
            <span aria-hidden className="h-5 w-5 animate-spin rounded-full border-2 border-brand-300 border-t-brand-700" />
            {step === "listing" ? `Asking ${SANDBOX_HOST} who has active prescriptions…` : "Reading the record and naming each medicine's ingredient…"}
          </p>
        </Card>
      )}

      {step === "patients" && (
        <Card className="p-5">
          <h3 className="font-serif text-xl font-semibold text-navy">Choose a synthetic patient</h3>
          <p className="mt-1 text-sm text-ink-soft">{patients.length} records on {SANDBOX_HOST} with active prescriptions, the busiest first.</p>
          <ul className="mt-3 divide-y divide-line">
            {patients.map((p) => (
              <li key={p.id} className="flex flex-wrap items-center justify-between gap-3 py-3">
                <div className="min-w-0">
                  <p className="font-medium text-ink">{p.name}</p>
                  <p className="break-words text-xs text-ink-muted">
                    {p.birthDate ? `born ${fmtDate(p.birthDate)} · ` : ""}{p.activeMedications} active {p.activeMedications === 1 ? "prescription" : "prescriptions"} · id {p.id}
                  </p>
                </div>
                <button type="button" onClick={() => void importPatient(p)} className="min-h-11 shrink-0 rounded-full bg-brand-700 px-4 text-sm font-semibold text-white hover:bg-brand-800">
                  Import for review
                </button>
              </li>
            ))}
          </ul>
          <button type="button" onClick={() => setStep("about")} className="mt-4 min-h-11 rounded-full px-4 text-sm font-semibold text-ink-soft ring-1 ring-line hover:bg-cream-dark">Back</button>
        </Card>
      )}

      {step === "error" && (
        <Card className="p-5" accent="border-l-attention">
          <p role="alert" className="font-semibold text-attention">{error}</p>
          <div className="mt-3 flex flex-wrap gap-2">
            <button type="button" onClick={() => void loadPatients()} className="min-h-11 rounded-full bg-brand-700 px-4 text-sm font-semibold text-white hover:bg-brand-800">Try again</button>
            <Link href="/passport/add/" className="inline-flex min-h-11 items-center rounded-full px-4 text-sm font-semibold text-ink-soft ring-1 ring-line hover:bg-cream-dark">Back to sources</Link>
          </div>
        </Card>
      )}

      {step === "done" && result && (
        <Card className="p-5" accent="border-l-good">
          <h3 className="font-serif text-xl font-semibold text-navy">Imported for your review</h3>
          {countItems(result.plan.newCounts) === 0 ? (
            <p className="mt-2 text-sm text-ink-soft">Everything in {result.sandboxPatient.name}&apos;s sandbox record is already in your Passport or already waiting in Review. Nothing new was added.</p>
          ) : (
            <p className="mt-2 text-sm text-ink-soft">
              <strong className="text-ink">{countItems(result.plan.newCounts)} items</strong> from {result.sandboxPatient.name}&apos;s record are waiting for you: {describeBatch(result.plan.newCounts).join(", ")}.
            </p>
          )}
          <dl className="mt-4 grid gap-2 text-sm sm:grid-cols-3">
            <div className="rounded-xl bg-cream/60 p-3">
              <dt className="text-xs font-semibold uppercase tracking-wider text-ink-muted">Mapped by Parthia</dt>
              <dd className="mt-0.5 text-ink">{result.counts.dictionary} {result.counts.dictionary === 1 ? "medicine" : "medicines"}</dd>
            </div>
            <div className="rounded-xl bg-cream/60 p-3">
              <dt className="text-xs font-semibold uppercase tracking-wider text-ink-muted">Mapped by RxNav (live)</dt>
              <dd className="mt-0.5 text-ink">
                {result.counts.rxnav} {result.counts.rxnav === 1 ? "medicine" : "medicines"}
                {result.counts.combinations > 0 && `, ${result.counts.combinations} ${result.counts.combinations === 1 ? "combination" : "combinations"}`}
              </dd>
            </div>
            <div className="rounded-xl bg-cream/60 p-3">
              <dt className="text-xs font-semibold uppercase tracking-wider text-ink-muted">Left unmapped</dt>
              <dd className="mt-0.5 text-ink">{result.counts.unmapped} {result.counts.unmapped === 1 ? "medicine" : "medicines"}</dd>
            </div>
          </dl>
          {result.counts.rxnav > 0 && (
            <p className="mt-3 text-sm text-ink-soft">
              Medicines named by the live lookup carry &ldquo;{RXNAV_PROVENANCE}&rdquo; on the item, next to the wording the server used, so you can
              check each one before confirming it.
            </p>
          )}
          {result.counts.unmapped > 0 && (
            <p className="mt-2 text-sm text-ink-soft">
              An unmapped medicine keeps the name the server gave it. Parthia will not match it to a medicine class, so it is left out of
              the safety questions rather than guessed at.
            </p>
          )}
          {countItems(result.plan.duplicates) > 0 && (
            <p className="mt-2 text-sm text-ink-muted">Already known, skipped: {describeBatch(result.plan.duplicates).join(", ")}.</p>
          )}
          <div className="mt-5 flex flex-wrap gap-2">
            <Link href="/passport/review/" className="inline-flex min-h-12 items-center rounded-full bg-brand-700 px-5 text-sm font-semibold text-white hover:bg-brand-800">Review now</Link>
            <button type="button" onClick={() => setStep("patients")} className="min-h-12 rounded-full px-5 text-sm font-semibold text-brand-700 ring-1 ring-line hover:bg-brand-50">Import another patient</button>
          </div>
        </Card>
      )}
      <Disclaimer />
    </div>
  );
}
